# Generated by Django 2.1.5 on 2019-01-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mailroom', '0003_auto_20190114_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('rollNo', models.CharField(max_length=40)),
                ('Mail_Id', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='otherdetail',
            name='user',
        ),
        migrations.DeleteModel(
            name='Otherdetail',
        ),
    ]
