# Generated by Django 2.1.5 on 2019-01-15 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mailroom', '0005_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='OTP',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
