# Generated by Django 2.1.5 on 2019-01-15 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mailroom', '0006_package_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retrieve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OTP', models.CharField(max_length=7)),
                ('RollNo', models.CharField(max_length=30)),
            ],
        ),
    ]
